apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: $NAMESPACE
spec:
  collectors:
    - redis:
        exclude: 'repl{{ ConfigOptionEquals "redis" "redis_embedded" }}'
        collectorName: redis
        uri: "redis://{{repl ConfigOption `redis_user` }}:{{repl ConfigOption `external_redis_password` }}@{{repl ConfigOption `redis_host` }}:{{repl ConfigOption `redis_port` }}"
  analyzers:
    - redis:
        exclude: 'repl{{ ConfigOptionEquals `redis` `redis_embedded` }}'
        checkName: "Must have a Redis database"
        collectorName: redis
        outcomes:
          - fail:
              when: connected == false
              message: "Cannot connect to Redis server"
          - pass:
              message: "Redis is ready"
    - jsonCompare:
        exclude: 'repl{{ ConfigOptionEquals `redis` `redis_embedded` }}'
        checkName: "Must have a Redis database"
        fileName: /redis/redis.json
        path: "isConnected"
        value: "false"
        outcomes:
          - fail:
              when: "false"
              message: Cannot connect to Redis server
          - pass:
              when: "true"
              message: Redis is ready

