apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: $NAMESPACE
spec:
  groups:
    - name: redisgroup
      title: Redis
      items:
        - name: redis_password
          hidden: true
          type: password
          value: '{{repl RandomString 32}}'

        - name: redis
          type: select_one
          title: Type
          required: true
          help_text: Would you like to use an embedded Redis instance, or connect to an external instance that you manage?
          items:
            - name: redis_embedded
              title: Embedded
            - name: redis_external
              title: External

        - name: redis_host
          title: Redis Host
          when: '{{repl ConfigOptionEquals "redis" "redis_external"}}'
          type: text
          required: true
          default: 'localhost'
        - name: redis_port
          title: Redis Port
          when: '{{repl ConfigOptionEquals "redis" "redis_external"}}'
          type: text
          default: '6379'
          required: true
        - name: redis_user
          title: Redis Username
          when: '{{repl ConfigOptionEquals "redis" "redis_external"}}'
          default: 'default'
          type: text
          required: true
        - name: external_redis_password
          title: Redis Password
          when: '{{repl ConfigOptionEquals "redis" "redis_external"}}'
          type: password
          default: '{{repl ConfigOption "redis_password"}}'
          required: true
        - name: redis_disk_size
          title: Disk size
          type: text
          required: true
          help_text: How much disk space should be provisioned for the redis instance? (e.g. 10Gi)
          when: '{{repl ConfigOptionEquals "redis" "redis_embedded"}}'

        - name: redis_resources
          type: select_one
          title: Resources
          help_text: How much resources would you like to allocate to the redis instance?
          when: '{{repl ConfigOptionEquals "redis" "redis_embedded"}}'
          default: redis_resources_default
          items:
            - name: redis_resources_default
              title: Default
            - name: redis_resources_custom
              title: Custom

        - name: resources_redis_request_cpu
          type: text
          title: CPU Request
          default: '100m'
          value: '100m'
          required: true
          when: '{{repl ConfigOptionEquals "redis_resources" "redis_resources_custom"}}'
        - name: resources_redis_limit_cpu
          type: text
          title: CPU Limit
          default: '500m'
          value: '500m'
          required: true
          when: '{{repl ConfigOptionEquals "redis_resources" "redis_resources_custom"}}'
        - name: resources_redis_request_memory
          type: text
          title: Memory Request
          default: '128Mi'
          value: '128Mi'
          required: true
          when: '{{repl ConfigOptionEquals "redis_resources" "redis_resources_custom"}}'
        - name: resources_redis_limit_memory
          type: text
          title: Memory Limit
          default: '512Mi'
          value: '512Mi'
          required: true
          when: '{{repl ConfigOptionEquals "redis_resources" "redis_resources_custom"}}'

